name: flutter_shop
description: Выполнение задачи
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  dots_indicator: ^2.0.0
  flutter_bloc: ^8.0.1
  formz: ^0.4.0
  equatable: ^2.0.0
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_services_binding: ^0.1.0
  intl: ^0.17.0
  flights_api:
    path: packages/flights_api
  flights_repository:
    path: packages/flights_repository
  local_storage_flights_api:
    path: packages/local_storage_flights_api
  flow_builder: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  mocktail: ^0.2.0
  flutter_lints: ^1.0.0
  mockingjay: ^0.2.0
  very_good_analysis: ^2.4.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
